[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run prebuild || true", "npm run build || true"]

[start]
cmd = "npm start"
